### ISSUE TITLE
docker-compose not expose ports

### ISSUE THREAD

**Issue by changchichung** [ngoduykhanh/wireguard-ui#134]
I just build the container in a new host
```
chchang@wg:~/git/wireguard-ui$ docker-compose up -d
Building wg
Sending build context to Docker daemon  333.8kB
Step 1/24 : FROM golang:1.16.7-alpine3.14 as builder
1.16.7-alpine3.14: Pulling from library/golang
a0d0a0d46f8b: Pull complete 
31adcdaf11c8: Pull complete 
b8b176561691: Pull complete 
ffa5077b735b: Pull complete 
2e51fde7a4ad: Pull complete 
....
....
....
Successfully built a6436af6a493
Successfully tagged wireguard-ui_wg:latest
WARNING: Image for service wg was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating wgui ... done
```
but this process did not expose 5000 port
```
chchang@wg:~/git/wireguard-ui$ docker ps -a
CONTAINER ID   IMAGE             COMMAND     CREATED         STATUS                   PORTS     NAMES
9aec7fceb209   wireguard-ui_wg   "./wg-ui"   3 minutes ago   Up 3 minutes (healthy)             wgui
chchang@wg:~/git/wireguard-ui$
```
but if I add ports in docker-compose.yml , this will conflict with network_mode: host.
```
chchang@wg:~/git/wireguard-ui$ docker-compose up -d
Creating wgui ... 

ERROR: for wgui  "host" network_mode is incompatible with port_bindings

ERROR: for wg  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 564, in execute_convergence_plan
  File "compose/service.py", line 480, in _execute_convergence_create
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 478, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[88262] Failed to execute script docker-compose
chchang@wg:~/git/wireguard-ui$ 
```
so , how to I connect to wgui ? and how do I change the open port ?

**Comment by N4v41** [comment]
in networkmode host docker cannot see which port are open, te port is exposed by the container, so just check in the host with netstat -an | grep 5000, or just try to access the app in the browser.
