### ISSUE TITLE
signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by bcodus** [ngoduykhanh/wireguard-ui#225]
I get this error on a fresh build on Ubuntu 20.04 VPS using with default options and ` go version go1.19.1 linux/amd64 `. 
 
 

 ```
~/wireguard-ui# ./wireguard-ui 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x79cb86]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc00016e000?, {0xc0000f8480?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0xa5f7e0, 0xc0000e4f00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0000f0a10, {0xa5f7e0?, 0xc0000e4f00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0xa5f7e0, 0xc0000e4f00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0xa60720?, 0xc000014060}, 0xdba06c)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0xa60720, 0xc000014060}, 0x0?)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00002e1a0?, 0xc0000b7d10?})
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/root/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
```

How can I fix it?

**Comment by vespian** [comment]
Check the golang version.

I have the same issue with Go 1.19 and it works for go 1.17.10.
